### ISSUE TITLE
Homepage search link to councils doesn't work

### ISSUE THREAD

**Issue by ajparsons** [mysociety/caps#272] opened 2022-01-20 15:23 UTC
Clicking the dropdown that appears when doing a search is broken:

![image](https://user-images.githubusercontent.com/8157058/150368167-59d215bb-8a58-48e8-b0eb-c9dbcd141e21.png)

Clicking the link does nothing.

**Comment by zarino** [comment] 2022-01-21 10:59
Oh dear, well a 404 on the javascript file would indeed explain it.

<img width="601" alt="Screenshot 2022-01-21 at 10 46 50" src="https://user-images.githubusercontent.com/739624/150514346-1ec9b363-1854-4e56-a55e-6682a4517215.png">

Since this all works locally, I’m guessing the 404 is being caused by a staticfiles pipeline misconfiguration. I know @struan had issues with something similar in the Scorecards deploy yesterday.

The original file _is_ available at `/static/caps/js/main.js`, but `{% javascript 'caps' %}` in the templates is returning `/static/js/caps.js` instead (as configured in `PIPELINE.JAVASCRIPT.caps.output_filename` in `proj/settings.py`) … I guess whatever copies/processes the file from the source location to the destination hasn’t run / isn’t running 🤔

**Comment by struan** [comment] 2022-01-24 11:41
Fixed in 28bb3ab

**Closed by struan** 2022-01-24 11:41 UTC
Labels: bug
