### ISSUE TITLE
20mph question display missing for some local authorities on Action Scorecards?

### ISSUE THREAD

**Issue by zarino** [mysociety/caps#632] opened 2024-02-20 14:46 UTC
From Isaac at CEUK:

> For **single-tier authorities** anyone that **did not** score positively on 20mph the question is missing from their council page…
> 
> So Barnet does not have the question there. Nor does Solihull.
> 
> This is not the case for county authorities, where it appears if they positively score or do not.

**Comment by struan** [comment] 2024-07-15 14:59
The problem is that the national data importer for that question didn't add the No answer for London Boroughs so all of them are missing from the data. I'd rather not re-run the importer so it might be best to fill those in by hand, then I can re-export the marks and re-import them. The authorities in question are:

 Barking and Dagenham Borough Council
 Barnet Borough Council
 Bexley Borough Council
 Brent Borough Council
 Bromley Council
 Enfield Borough Council
 Greenwich Borough Council
 Harrow Borough Council
 Havering Borough Council
 Hillingdon Borough Council
 Redbridge Borough Council
 Sutton Borough Council

**Comment by zarino** [comment] 2024-07-16 08:16
@struan If this only affects London Boroughs, why doesn’t Question 2.4 appear on [the page for Solihull MBC](https://councilclimatescorecards.uk/councils/solihull-metropolitan-borough-council/)?

**Comment by struan** [comment] 2024-07-16 08:48
@zarino oh, looks like it's also missing from Metropolitan Districts too so the full list is:

Barking and Dagenham Borough Council
 Barnet Borough Council
 Barnsley Borough Council
 Bexley Borough Council
 Dudley Borough Council
 Brent Borough Council
 Bromley Council
 Enfield Borough Council
 Gateshead Borough Council
 Greenwich Borough Council
 Harrow Borough Council
 Havering Borough Council
 Hillingdon Borough Council
 Kirklees Borough Council
 Knowsley Borough Council
 North Tyneside Borough Council
 Redbridge Borough Council
 Rotherham Borough Council
 Salford City Council
 Sandwell Borough Council
 Solihull Borough Council
 Sunderland City Council
 Sutton Borough Council
 Tameside Borough Council
 Oldham Borough Council
 Trafford Borough Council
 Wakefield City Council
 Walsall Borough Council
 Wolverhampton City Council

**Comment by struan** [comment] 2024-07-25 15:01
Fixed via https://github.com/mysociety/ceuk-marking/commit/25d2fb7e8b23faba8353bde25a9c37aa5e5ace5a and the export/import of scores.

**Closed by struan** 2024-07-25 15:01 UTC
Labels: bug, project:scorecards
