### ISSUE TITLE
CAPE: Icon navbar mobile not showing

### ISSUE THREAD

**Issue by lucascumsille** [mysociety/caps#474] opened 2023-01-26 07:09 UTC
On chrome and safari mobile

![Image](https://user-images.githubusercontent.com/13790153/214776952-f805b767-1022-411f-b7ef-80b8afb76bb3.png)

**Comment by lucascumsille** [comment] 2023-01-26 07:11
@zarino I could tackle this when changing the icon for the 20th anniversary.

**Comment by zarino** [comment] 2023-01-26 09:11
This is a duplicate of https://github.com/mysociety/caps/issues/462.

We thought https://github.com/mysociety/caps/pull/463 might fix it, but on closer inspection, it seems unlikely.

The missing menu image is a result of the Django Pipeline package stripping whitespace out of the _inside_ of SVG tags, when those SVGs are inlined inside Sass files.

**Closed by zarino** 2023-01-26 09:11 UTC
